version: '3.3'
services:
  # order-service and its Dapr sidecar
  # zipkin

  ############################
  # order-service and its Dapr sidecar
  ############################
  order-service:
    image: order-service
    build:
      context: rest-controller
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - 9200:9200
    networks:
      - order-service

  order-service-dapr:
    image: daprio/daprd:edge
    container_name: Dapr.Sidecar-order-service
    command: ["./daprd",
              "-app-id", "order-service",
              "-app-port", "9200",
              "-config", "/dapr-components/config.yaml",
              "-log-level", "debug",
              "-components-path", "/dapr-components"]
    volumes:
      - "./dapr-components:/dapr-components"
    depends_on:
      - order-service
    network_mode: "service:order-service"

  zipkin:
    image: openzipkin/zipkin-slim

  ############################
  # Redis (commented out as we are using a public mqtt broker for testing, no need for local instance of redis or mosquitto)
  ############################
#  redis:
#    image: redis:alpine
#    container_name: Dapr.redis
#    ports:
#      - "6379"
#    networks:
#      - order-service

networks:
  order-service:
    external:
      name: local_order_service